config/routes.rb
RailsBootstrap::Application.routes.draw do
  resources :admins

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"} 
  #   devise_scope :user do
#    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  resources :contact_us

  resources :preview_sign_ups

  resources :itineraries do
    collection do
      get 'listing/:id', :to => 'itineraries#listing'
    end
  end

  resources :invited_to_trips do
    collection do
      post 'invite'
      post 'invite/:id', :to => 'invited_to_trips#invite'
    end
  end
  resources :orders
  resources :friend_lists do
    collection do
      post 'invite_friend'
      post 'invite_friend/:id', :to => 'friend_lists#invite_friend'
    end
  end
  resources :galleries
  resources :categories
  resources :destinations  
  resources :user_wants
  resources :merchants
  resources :products
  resources :product_price_lists
  # resources :user_shopping_carts
  resources :trips do
    collection do
      post 'update_trip_date/:id', :to => 'trips#update_trip_date'
    end
  end
  resources :product_in_feeds  

  resources :feeds  
  resources :trending_tags
  resources :feeds do
      collection do
      get 'listing/:id', :to => 'feeds#listing'
      post 'listing/:id', :to => 'feeds#listing'
      get 'location/:id', :to => 'feeds#location'
      
      post 'create_feed'
   end
  end
  resources :products do
	  collection do
      get 'shop'
	    get 'shop/:id' , :to => 'products#shop'
	    get 'want/:id' , :to => 'products#want'
      get 'item/:id' , :to => 'products#item'
      get 'preview/:id', :to => 'products#preview'
      post 'create_product'
	  end
  end
  resources :user_shopping_carts do
    collection do
      get 'cart' , :to => 'user_shopping_carts#cart'
      get 'clearcart', :to => 'user_shopping_carts#clearcart'
      get 'buy', :to => 'user_shopping_carts#buy'
      get 'thankyou', :to => 'user_shopping_carts#thankyou'
      get 'receive', :to => 'user_shopping_carts#receive'
      get 'cancel', :to => 'user_shopping_carts#cancel'
      post 'change_quantity', :to => 'user_shopping_carts#change_quantity'
      get 'empty', :to => 'user_shopping_carts#empty'
      get 'remove/:id', :to => 'user_shopping_carts#remove'
    end
  end
  # resources :products, :only => [:shop], :defaults => { :format => 'json'}
  resources :user_details do
    collection do
      get 'trips' , :to => 'user_details#trips'
      get 'settings/:id', :to => 'user_details#settings'
    end
  end

  match 'display/:id' => 'visitors#display', via: [:get, :post]
  match 'new' => 'visitors#new', via: [:get]
  match 'new' => 'visitors#landingsignup', via: [:get, :post]
  match 'account' => 'visitors#account', via: [:get]
  match 'aboutus' => 'visitors#aboutus', via: [:get]
  match 'contact' => 'contact_us#contact', via: [:get, :post]
  root :to => 'preview#landing'
  # devise_for :users, :controllers => {:registrations => "registrations"} do
  #   get "/users/sign_up" => "authentications#index"
  #   get "/users/sign_in" => "authentications#index"
  # end
  
#  get "user_feeds/home"  resources :users, only: [:show, :edit, :update]
end

app/models/product_price_list.rb
class ProductPriceList < ActiveRecord::Base
end

app/controllers/product_price_lists_controller.rb
class ProductPriceListsController < ApplicationController
  before_action :set_product_price_list, only: [:show, :edit, :update, :destroy]

  # GET /product_price_lists
  # GET /product_price_lists.json
  def index
    @product_price_lists = ProductPriceList.all
  end

  # GET /product_price_lists/1
  # GET /product_price_lists/1.json
  def show
  end

  # GET /product_price_lists/new
  def new
    @product_price_list = ProductPriceList.new
  end

  # GET /product_price_lists/1/edit
  def edit
  end

  # POST /product_price_lists
  # POST /product_price_lists.json
  def create
    @product_price_list = ProductPriceList.new(product_price_list_params)

    respond_to do |format|
      if @product_price_list.save
        format.html { redirect_to @product_price_list, notice: 'Product price list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_price_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_price_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_price_lists/1
  # PATCH/PUT /product_price_lists/1.json
  def update
    respond_to do |format|
      if @product_price_list.update(product_price_list_params)
        format.html { redirect_to @product_price_list, notice: 'Product price list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_price_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_price_lists/1
  # DELETE /product_price_lists/1.json
  def destroy
    @product_price_list.destroy
    respond_to do |format|
      format.html { redirect_to product_price_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_price_list
      @product_price_list = ProductPriceList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_price_list_params
      params.require(:product_price_list).permit(:Price, :DayOfYear)
    end
end

app/helpers/product_price_lists_helper.rb
module ProductPriceListsHelper
end

app/views/product_price_lists/_form.html.erb
<%= simple_form_for(@product_price_list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Price %>
    <%= f.input :DayOfYear %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_price_lists/edit.html.erb
<h1>Editing product_price_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_price_list %> |
<%= link_to 'Back', product_price_lists_path %>

app/views/product_price_lists/index.html.erb
<h1>Listing product_price_lists</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Dayofyear</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_price_lists.each do |product_price_list| %>
      <tr>
        <td><%= product_price_list.Price %></td>
        <td><%= product_price_list.DayOfYear %></td>
        <td><%= link_to 'Show', product_price_list %></td>
        <td><%= link_to 'Edit', edit_product_price_list_path(product_price_list) %></td>
        <td><%= link_to 'Destroy', product_price_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product price list', new_product_price_list_path %>

app/views/product_price_lists/new.html.erb
<h1>New product_price_list</h1>

<%= render 'form' %>

<%= link_to 'Back', product_price_lists_path %>

app/views/product_price_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @product_price_list.Price %>
</p>

<p>
  <strong>Dayofyear:</strong>
  <%= @product_price_list.DayOfYear %>
</p>

<%= link_to 'Edit', edit_product_price_list_path(@product_price_list) %> |
<%= link_to 'Back', product_price_lists_path %>