config/routes.rb
RailsBootstrap::Application.routes.draw do
  resources :admins

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"} 
  #   devise_scope :user do
#    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  resources :contact_us

  resources :preview_sign_ups

  resources :itineraries do
    collection do
      get 'listing/:id', :to => 'itineraries#listing'
    end
  end

  resources :invited_to_trips do
    collection do
      post 'invite'
      post 'invite/:id', :to => 'invited_to_trips#invite'
    end
  end
  resources :orders
  resources :friend_lists do
    collection do
      post 'invite_friend'
      post 'invite_friend/:id', :to => 'friend_lists#invite_friend'
    end
  end
  resources :galleries
  resources :categories
  resources :destinations  
  resources :user_wants
  resources :merchants
  resources :products
  resources :product_price_lists
  # resources :user_shopping_carts
  resources :trips do
    collection do
      post 'update_trip_date/:id', :to => 'trips#update_trip_date'
    end
  end
  resources :product_in_feeds  

  resources :feeds  
  resources :trending_tags
  resources :feeds do
      collection do
      get 'listing/:id', :to => 'feeds#listing'
      post 'listing/:id', :to => 'feeds#listing'
      get 'location/:id', :to => 'feeds#location'
      
      post 'create_feed'
   end
  end
  resources :products do
	  collection do
      get 'shop'
	    get 'shop/:id' , :to => 'products#shop'
	    get 'want/:id' , :to => 'products#want'
      get 'item/:id' , :to => 'products#item'
      get 'preview/:id', :to => 'products#preview'
      post 'create_product'
	  end
  end
  resources :user_shopping_carts do
    collection do
      get 'cart' , :to => 'user_shopping_carts#cart'
      get 'clearcart', :to => 'user_shopping_carts#clearcart'
      get 'buy', :to => 'user_shopping_carts#buy'
      get 'thankyou', :to => 'user_shopping_carts#thankyou'
      get 'receive', :to => 'user_shopping_carts#receive'
      get 'cancel', :to => 'user_shopping_carts#cancel'
      post 'change_quantity', :to => 'user_shopping_carts#change_quantity'
      get 'empty', :to => 'user_shopping_carts#empty'
      get 'remove/:id', :to => 'user_shopping_carts#remove'
    end
  end
  # resources :products, :only => [:shop], :defaults => { :format => 'json'}
  resources :user_details do
    collection do
      get 'trips' , :to => 'user_details#trips'
      get 'settings/:id', :to => 'user_details#settings'
    end
  end

  match 'display/:id' => 'visitors#display', via: [:get, :post]
  match 'new' => 'visitors#new', via: [:get]
  match 'new' => 'visitors#landingsignup', via: [:get, :post]
  match 'account' => 'visitors#account', via: [:get]
  match 'aboutus' => 'visitors#aboutus', via: [:get]
  match 'contact' => 'contact_us#contact', via: [:get, :post]
  root :to => 'preview#landing'
  # devise_for :users, :controllers => {:registrations => "registrations"} do
  #   get "/users/sign_up" => "authentications#index"
  #   get "/users/sign_in" => "authentications#index"
  # end
  
#  get "user_feeds/home"  resources :users, only: [:show, :edit, :update]
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  before_action :set_contact_u, only: [:show, :edit, :update, :destroy]
  def contact
    if request.post?
      first_name = params[:ContactUsFirstName]
      last_name = params[:ContactUsLastName]
      email = params[:ContactUsEmail]
      comment = params[:ContactUsComments]
      contact_us = ContactU.where(:FirstName => first_name, :LastName => last_name, :Email => email, :Comment => comment ).take
      if contact_us == nil
        contact_us = ContactU.new(:FirstName => first_name, :LastName => last_name, :Email => email, :Comment => comment )
        contact_us.save
        @notice = "Message successfully created, we will process it shortly."
        # flash[:notice] = "Message successfully created, we will process it shortly."
      end 
    end
  end
  # GET /contact_us
  # GET /contact_us.json
  def index
    @contact_us = ContactU.all
  end

  # GET /contact_us/1
  # GET /contact_us/1.json
  def show
  end

  # GET /contact_us/new
  def new
    @contact_u = ContactU.new
  end

  # GET /contact_us/1/edit
  def edit
  end

  # POST /contact_us
  # POST /contact_us.json
  def create
    @contact_u = ContactU.new(contact_u_params)

    respond_to do |format|
      if @contact_u.save
        format.html { redirect_to @contact_u, notice: 'Contact u was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_u }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_us/1
  # PATCH/PUT /contact_us/1.json
  def update
    respond_to do |format|
      if @contact_u.update(contact_u_params)
        format.html { redirect_to @contact_u, notice: 'Contact u was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_us/1
  # DELETE /contact_us/1.json
  def destroy
    @contact_u.destroy
    respond_to do |format|
      format.html { redirect_to contact_us_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_u
      @contact_u = ContactU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_u_params
      params.require(:contact_u).permit(:FirstName, :LastName, :Email, :Comment)
    end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/views/contact_us/_form.html.erb
<%= simple_form_for(@contact_u) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :FirstName %>
    <%= f.input :LastName %>
    <%= f.input :Email %>
    <%= f.input :Comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_us/contact.html.erb
<%= js add_gritter(@notice, :image => :success, :title => "Success!", :sticky => true) %>
<h1 class="pink-call">
	<span class="brand-wish-color">Contact</span><span class="brand-able-color"> Us</span>
</h1>
<div class="row">
	<div class="col-md-6">
		
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3983.7094815355936!2d101.66651000000003!3d3.1709970000000047!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc485e05b0eee5%3A0x3dfac552f3cd566d!2sSolaris+Dutamas!5e0!3m2!1sen!2s!4v1396058095997" width="400" height="300" frameborder="0" style="border:0"></iframe>
	</div>
	<div class="col-md-6">
			<p class="large-text brand-wish">
				Office Address:




			</p>
			<p>
<pre class="noborder medium-text nopadding-left">
Touristly
C3-5-3A,
Solaris Dutamas,
Jalan Dutamas 1,
50480 Kuala Lumpur.</pre>
			</p>
			<p class="large-text brand-wish">
				Email: 
			</p>
			<p>
info@touritsly.com 
			</p>
	</div>
</div>
<div class="listing-section"></div>
<div class="row">
	<p>HAVE A QUESTION? EMAIL US!</p>
	
	<%= form_tag({controller: "contact_us", action: "contact" }, id: "contact_us_form", method: "post", class:"form-horizontal", role:"form") do %>
	<div class="form-group">
	   <label class="col-sm-2 control-label" for="ContactUsFirstName">First Name</label>
	   <div class="col-sm-10">
	   	<%= text_field_tag 'ContactUsFirstName', nil, :type => "text", :class=>"form-control", :required => true , :placeholder=>"Bob" %>
	   </div>
	</div>
	<div class="form-group">
	   <label class="col-sm-2 control-label" for="ContactUsLastName">Last Name</label>
	   <div class="col-sm-10">
	   	<%= text_field_tag 'ContactUsLastName', nil, :type => "text", :class=>"form-control", :required => true , :placeholder=>"Smith" %>
	   </div>
	</div>
	<div class="form-group">
	   <label class="col-sm-2 control-label" for="ContactUsEmail">Email</label>
	   <div class="col-sm-10">
	   	<%= text_field_tag 'ContactUsEmail', nil, :type => "email", :class=>"form-control", :required => true , :placeholder=>"bobsmith@gmail.com" %>
	   </div>
	</div>
	
	<div class="form-group">
	   <label for="ContactUsComments" class="col-sm-2 control-label">Questions/Comments</label>
	   <div class="col-sm-10">
	   	<%= text_area_tag 'ContactUsComments', nil, :rows => "3", :class=>"form-control", :required => true , :placeholder=>"Comments"  %>
	   </div>
	</div>
	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </div>
  <% end %>
</div>
	

app/views/contact_us/edit.html.erb
<h1>Editing contact_u</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_u %> |
<%= link_to 'Back', contact_us_path %>

app/views/contact_us/index.html.erb
<h1>Listing contact_us</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_us.each do |contact_u| %>
      <tr>
        <td><%= contact_u.FirstName %></td>
        <td><%= contact_u.LastName %></td>
        <td><%= contact_u.Email %></td>
        <td><%= contact_u.Comment %></td>
        <td><%= link_to 'Show', contact_u %></td>
        <td><%= link_to 'Edit', edit_contact_u_path(contact_u) %></td>
        <td><%= link_to 'Destroy', contact_u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact u', new_contact_u_path %>

app/views/contact_us/new.html.erb
<h1>New contact_u</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_us_path %>

app/views/contact_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @contact_u.FirstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact_u.LastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_u.Email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @contact_u.Comment %>
</p>

<%= link_to 'Edit', edit_contact_u_path(@contact_u) %> |
<%= link_to 'Back', contact_us_path %>