config/routes.rb
RailsBootstrap::Application.routes.draw do
  resources :admins

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"} 
  #   devise_scope :user do
#    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  resources :contact_us

  resources :preview_sign_ups

  resources :itineraries do
    collection do
      get 'listing/:id', :to => 'itineraries#listing'
    end
  end

  resources :invited_to_trips do
    collection do
      post 'invite'
      post 'invite/:id', :to => 'invited_to_trips#invite'
    end
  end
  resources :orders
  resources :friend_lists do
    collection do
      post 'invite_friend'
      post 'invite_friend/:id', :to => 'friend_lists#invite_friend'
    end
  end
  resources :galleries
  resources :categories
  resources :destinations  
  resources :user_wants
  resources :merchants
  resources :products
  resources :product_price_lists
  # resources :user_shopping_carts
  resources :trips do
    collection do
      post 'update_trip_date/:id', :to => 'trips#update_trip_date'
    end
  end
  resources :product_in_feeds  

  resources :feeds  
  resources :trending_tags
  resources :feeds do
      collection do
      get 'listing/:id', :to => 'feeds#listing'
      post 'listing/:id', :to => 'feeds#listing'
      get 'location/:id', :to => 'feeds#location'
      
      post 'create_feed'
   end
  end
  resources :products do
	  collection do
      get 'shop'
	    get 'shop/:id' , :to => 'products#shop'
	    get 'want/:id' , :to => 'products#want'
      get 'item/:id' , :to => 'products#item'
      get 'preview/:id', :to => 'products#preview'
      post 'create_product'
	  end
  end
  resources :user_shopping_carts do
    collection do
      get 'cart' , :to => 'user_shopping_carts#cart'
      get 'clearcart', :to => 'user_shopping_carts#clearcart'
      get 'buy', :to => 'user_shopping_carts#buy'
      get 'thankyou', :to => 'user_shopping_carts#thankyou'
      get 'receive', :to => 'user_shopping_carts#receive'
      get 'cancel', :to => 'user_shopping_carts#cancel'
      post 'change_quantity', :to => 'user_shopping_carts#change_quantity'
      get 'empty', :to => 'user_shopping_carts#empty'
      get 'remove/:id', :to => 'user_shopping_carts#remove'
    end
  end
  # resources :products, :only => [:shop], :defaults => { :format => 'json'}
  resources :user_details do
    collection do
      get 'trips' , :to => 'user_details#trips'
      get 'settings/:id', :to => 'user_details#settings'
    end
  end

  match 'display/:id' => 'visitors#display', via: [:get, :post]
  match 'new' => 'visitors#new', via: [:get]
  match 'new' => 'visitors#landingsignup', via: [:get, :post]
  match 'account' => 'visitors#account', via: [:get]
  match 'aboutus' => 'visitors#aboutus', via: [:get]
  match 'contact' => 'contact_us#contact', via: [:get, :post]
  root :to => 'preview#landing'
  # devise_for :users, :controllers => {:registrations => "registrations"} do
  #   get "/users/sign_up" => "authentications#index"
  #   get "/users/sign_in" => "authentications#index"
  # end
  
#  get "user_feeds/home"  resources :users, only: [:show, :edit, :update]
end

app/models/friend_list.rb
class FriendList < ActiveRecord::Base
end

app/controllers/friend_lists_controller.rb
class FriendListsController < ApplicationController
  before_action :set_friend_list, only: [:show, :edit, :update, :destroy]

  def invite_friend
    friend_user_id = params[:userid]
    friend_user_id.each do |el|
       new_friend = FriendList.where(UserId:current_user.id, FriendUserId:el).take
       if new_friend == nil
        new_friend = FriendList.create(UserId:current_user.id, FriendUserId:el)
        new_friend.save
       end
    end
  end

  # GET /friend_lists
  # GET /friend_lists.json
  def index
    @friend_lists = FriendList.all
  end

  # GET /friend_lists/1
  # GET /friend_lists/1.json
  def show
  end

  # GET /friend_lists/new
  def new
    @friend_list = FriendList.new
  end

  # GET /friend_lists/1/edit
  def edit
  end

  # POST /friend_lists
  # POST /friend_lists.json
  def create
    @friend_list = FriendList.new(friend_list_params)

    respond_to do |format|
      if @friend_list.save
        format.html { redirect_to @friend_list, notice: 'Friend list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friend_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_lists/1
  # PATCH/PUT /friend_lists/1.json
  def update
    respond_to do |format|
      if @friend_list.update(friend_list_params)
        format.html { redirect_to @friend_list, notice: 'Friend list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_lists/1
  # DELETE /friend_lists/1.json
  def destroy
    @friend_list.destroy
    respond_to do |format|
      format.html { redirect_to friend_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_list
      @friend_list = FriendList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_list_params
      params.require(:friend_list).permit(:UserId, :FriendUserId)
    end
end

app/helpers/friend_lists_helper.rb
module FriendListsHelper
end

app/views/friend_lists/_form.html.erb
<%= simple_form_for(@friend_list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :UserId %>
    <%= f.input :FriendUserId %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/friend_lists/edit.html.erb
<h1>Editing friend_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend_list %> |
<%= link_to 'Back', friend_lists_path %>

app/views/friend_lists/index.html.erb
<h1>Listing friend_lists</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Frienduserid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_lists.each do |friend_list| %>
      <tr>
        <td><%= friend_list.UserId %></td>
        <td><%= friend_list.FriendUserId %></td>
        <td><%= link_to 'Show', friend_list %></td>
        <td><%= link_to 'Edit', edit_friend_list_path(friend_list) %></td>
        <td><%= link_to 'Destroy', friend_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend list', new_friend_list_path %>

app/views/friend_lists/new.html.erb
<h1>New friend_list</h1>

<%= render 'form' %>

<%= link_to 'Back', friend_lists_path %>

app/views/friend_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @friend_list.UserId %>
</p>

<p>
  <strong>Frienduserid:</strong>
  <%= @friend_list.FriendUserId %>
</p>

<%= link_to 'Edit', edit_friend_list_path(@friend_list) %> |
<%= link_to 'Back', friend_lists_path %>