config/routes.rb
RailsBootstrap::Application.routes.draw do
  resources :admins

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"} 
  #   devise_scope :user do
#    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  resources :contact_us

  resources :preview_sign_ups

  resources :itineraries do
    collection do
      get 'listing/:id', :to => 'itineraries#listing'
    end
  end

  resources :invited_to_trips do
    collection do
      post 'invite'
      post 'invite/:id', :to => 'invited_to_trips#invite'
    end
  end
  resources :orders
  resources :friend_lists do
    collection do
      post 'invite_friend'
      post 'invite_friend/:id', :to => 'friend_lists#invite_friend'
    end
  end
  resources :galleries
  resources :categories
  resources :destinations  
  resources :user_wants
  resources :merchants
  resources :products
  resources :product_price_lists
  # resources :user_shopping_carts
  resources :trips do
    collection do
      post 'update_trip_date/:id', :to => 'trips#update_trip_date'
    end
  end
  resources :product_in_feeds  

  resources :feeds  
  resources :trending_tags
  resources :feeds do
      collection do
      get 'listing/:id', :to => 'feeds#listing'
      post 'listing/:id', :to => 'feeds#listing'
      get 'location/:id', :to => 'feeds#location'
      
      post 'create_feed'
   end
  end
  resources :products do
	  collection do
      get 'shop'
	    get 'shop/:id' , :to => 'products#shop'
	    get 'want/:id' , :to => 'products#want'
      get 'item/:id' , :to => 'products#item'
      get 'preview/:id', :to => 'products#preview'
      post 'create_product'
	  end
  end
  resources :user_shopping_carts do
    collection do
      get 'cart' , :to => 'user_shopping_carts#cart'
      get 'clearcart', :to => 'user_shopping_carts#clearcart'
      get 'buy', :to => 'user_shopping_carts#buy'
      get 'thankyou', :to => 'user_shopping_carts#thankyou'
      get 'receive', :to => 'user_shopping_carts#receive'
      get 'cancel', :to => 'user_shopping_carts#cancel'
      post 'change_quantity', :to => 'user_shopping_carts#change_quantity'
      get 'empty', :to => 'user_shopping_carts#empty'
      get 'remove/:id', :to => 'user_shopping_carts#remove'
    end
  end
  # resources :products, :only => [:shop], :defaults => { :format => 'json'}
  resources :user_details do
    collection do
      get 'trips' , :to => 'user_details#trips'
      get 'settings/:id', :to => 'user_details#settings'
    end
  end

  match 'display/:id' => 'visitors#display', via: [:get, :post]
  match 'new' => 'visitors#new', via: [:get]
  match 'new' => 'visitors#landingsignup', via: [:get, :post]
  match 'account' => 'visitors#account', via: [:get]
  match 'aboutus' => 'visitors#aboutus', via: [:get]
  match 'contact' => 'contact_us#contact', via: [:get, :post]
  root :to => 'preview#landing'
  # devise_for :users, :controllers => {:registrations => "registrations"} do
  #   get "/users/sign_up" => "authentications#index"
  #   get "/users/sign_in" => "authentications#index"
  # end
  
#  get "user_feeds/home"  resources :users, only: [:show, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:Name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.Name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.Name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>